name: pyrocb
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.12
  - pytorch
  - torchvision
  - torchaudio
  - xarray
  - xeofs
  - pandas
  - numpy
  - scikit-learn
  - scipy
  - matplotlib
  - seaborn
  - ipdb
  - tqdm
  - dask
  - netcdf4
  - h5netcdf
  - herbie-data
  - bottleneck
  - zarr
  - fsspec
  - jupyter
  - ipython
  - openpyxl
  - pip
  - pip:
    - affine
    - rasterio
    - rioxarray
    - earthaccess